//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmploye
    {
        public int EmployeID { get; set; }
        public Nullable<int> AllIDemp { get; set; }
        public Nullable<int> EmployeFlor { get; set; }
        public string Gender { get; set; }
        public Nullable<int> Salary { get; set; }
        public string Citizenship { get; set; }
        public string Engagment { get; set; }
    
        public virtual tblAll tblAll { get; set; }
    }
}
